### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by hexylena**
- [x] Fix pypi credentials
- [x] Ask bioblend to make a release

# Missing Parameters

E.g. `parsec history update_history` was missing numerous params that are [documented in help but are not in the argspec](http://bioblend.readthedocs.io/en/latest/api_docs/galaxy/all.html#bioblend.galaxy.histories.HistoryClient.update_history).

These are now fixed and function.

# JSON Inputs

Previously json inputs did not function. Now they do. Additionally loading from stdin, file, or raw string is supported. E.g. all of these will function the same:

```console
cat params.json | parsec jobs search_jobs -; # Stdin
parsec jobs search_jobs params.json; # Filename
parsec jobs search_jobs $(cat params.json); # String argument
```

# Better Example

I've [added an example](https://github.com/galaxy-iuc/parsec/tree/fix-number-2#in-depth-example) where I create a history, run a tool, and the launch a workflow and check its status in the terminal.

# Shinier Docs

- https://parsec.readthedocs.io/en/dev/readme.html
- https://parsec.readthedocs.io/en/dev/commands.html

# CLI Simplification

moved commands into subcommands. No longer do you get this gigantic list of a thousand things you can do, instead just:

utvalg_069

and then the subcommands are further refined:

utvalg_070

### CODE REVIEW

**Comment by hexylena** [comment]
cc @natefoo or @jmchilton or someone? Would it be possible to get this package onto pypi under the same namespace as the rest of the Galaxy stuff (i.e. without leaving my repo access as a SPOF). I've added my deployment information for pypi using travis to automatically release tagged builds, but if one of y'all could just commit on top with the correct information. I use the `travis` [CLI tool](https://github.com/travis-ci/travis.rb) to configure this with `travis setup pypi`.

(Or should the IUC register a separate pypi account?)

**Comment by hexylena** [comment]
Merging this to dev, the merge to master will need to solve the bullets from the origin issue.

**Comment by jmchilton** [comment]
@erasche We need to get better about this ourselves - we don't have a Galaxy account or namespace as far as I am aware. Planemo is just me and Nate, ephemeris is just me. I'll try to add a few more people to all of "my projects".

**Comment by hexylena** [comment]
Oh, somehow I just assumed there was one. In that case I'll do the same and add y'all.

**Pull request merged**
