### PR TITLE
Add options for init command

### PR DESCRIPTION
**Pull request by manabuishii**

### CODE REVIEW

**Comment by manabuishii** [comment]
hmm -f (--path) can works well at init.
But not work in other command.
It needs to support global level , I think.

**Comment by hexylena** [comment]
@manabuishii correct, you'd want to add it here https://github.com/galaxy-iuc/parsec/blob/master/parsec/cli.py#L103

**Comment by hexylena** [comment]
Sorry for the delay @manabuishii, everything looks good!

**Comment by hexylena** [comment]
this is now part of the 1.0.2 release available on pypi. Thanks again @manabuishii!

**Pull request merged**
