### PR TITLE
1.0.0 Release

### PR DESCRIPTION
**Pull request by hexylena**
# TODO before release:

- [x] Fix pypi credentials
- [x] Ask bioblend to make a new release. Ping @nsoranzo (e.g. otherwise renaming datasets doesn't work https://github.com/galaxyproject/bioblend/issues/213)
- [x] await new bioblend release

# Missing Parameters

E.g. `parsec history update_history` was missing numerous params that are [documented in help but are not in the argspec](http://bioblend.readthedocs.io/en/latest/api_docs/galaxy/all.html#bioblend.galaxy.histories.HistoryClient.update_history).

These are now fixed and function.

# JSON Inputs

Previously json inputs did not function. Now they do. Additionally loading from stdin, file, or raw string is supported. E.g. all of these will function the same:

```console
cat params.json | parsec jobs search_jobs -; # Stdin
parsec jobs search_jobs params.json; # Filename
parsec jobs search_jobs $(cat params.json); # String argument
```

# Better Example

I've [added an example](https://github.com/galaxy-iuc/parsec/tree/dev#in-depth-example) where I create a history, run a tool, and the launch a workflow and check its status in the terminal.

# Shinier Docs

- https://parsec.readthedocs.io/en/dev/readme.html
- https://parsec.readthedocs.io/en/dev/commands.html

# CLI Simplification

moved commands into subcommands. No longer do you get this gigantic list of a thousand things you can do, instead just:

utvalg_069

and then the subcommands are further refined:

utvalg_070

### CODE REVIEW

**Comment by hexylena** [comment]
@bgruening @mvdbeek both of you have used this yes? I don't suppose either of you would mind testing it out before I release?

**Comment by bgruening** [comment]
I can test this, for sure! How much time to I have? :)

**Comment by hexylena** [comment]
Hmm, I had not picked a date. Probably I will merge this next week, just want it to be in the release notes and maybe get some publicity.

**Comment by hexylena** [comment]
Almost ready to release. Thanks @nsoranzo for the bioblend release. @bgruening any concerns after your recent test? Anyone else in IUC want to try it out? It is starting to be a very nice toolkit

**Comment by hexylena** [comment]
@bgruening https://github.com/galaxy-iuc/parsec/blob/dev/docs/cookbook.rst#capturing-execution-state-as-xunit-output

**Comment by bgruening** [comment]
@erasche release!!! This is an amazing project! Let's get it out!

**Pull request merged**
